import { ReasonCode } from './reason-codes';

interface DisputeData {
  merchantName: string;
  orderId: string;
  customerName: string;
  transactionDate: string;
  transactionAmount: number;
  cardNetwork: string;
  reasonCode: string;
  reasonCodeData: ReasonCode;
  disputeDate: string;
  responseDeadline: string;
  evidenceItems: Array<{
    type: string;
    description?: string;
    contentText?: string;
    isProvided: boolean;
  }>;
}

export function generateResponseLetter(data: DisputeData): string {
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const amount = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(data.transactionAmount);

  const providedItems = data.evidenceItems.filter(item => item.isProvided);

  const evidenceList = providedItems.map((item, idx) => {
    const typeLabel = item.type.replace(/_/g, ' ').replace(/\b\w/g, (l: string) => l.toUpperCase());
    return `${idx + 1}. **${typeLabel}**: ${item.description || 'Provided as supporting documentation'}`;
  }).join('\n');

  return `CHARGEBACK RESPONSE LETTER
==========================

Date: ${today}
Re: Chargeback Dispute Response
Merchant: ${data.merchantName}
Order ID: ${data.orderId}
Transaction Date: ${data.transactionDate}
Transaction Amount: ${amount}
Card Network: ${data.cardNetwork.toUpperCase()}
Reason Code: ${data.reasonCode} — ${data.reasonCodeData.name}
Dispute Date: ${data.disputeDate}
Response Deadline: ${data.responseDeadline}

---

MERCHANT IDENTIFICATION
-----------------------
${data.merchantName} (hereinafter "the Merchant") submits this response to the chargeback filed under ${data.cardNetwork.toUpperCase()} Reason Code ${data.reasonCode} (${data.reasonCodeData.name}) for Order #${data.orderId} in the amount of ${amount}.

DISPUTE REFERENCE
-----------------
The Merchant disputes this chargeback and respectfully requests a reversal based on the evidence presented herein. The transaction was legitimate, properly authorized, and fulfilled in accordance with the cardholder's order.

Transaction Details:
- Order ID: ${data.orderId}
- Customer: ${data.customerName}
- Transaction Date: ${data.transactionDate}
- Transaction Amount: ${amount}
- Card Network: ${data.cardNetwork.toUpperCase()}

REASON CODE ACKNOWLEDGMENT
--------------------------
The Merchant acknowledges this dispute is filed under Reason Code ${data.reasonCode}: ${data.reasonCodeData.name}. ${data.reasonCodeData.description}

EVIDENCE SUMMARY
----------------
The Merchant provides the following evidence in support of this response:

${evidenceList || 'No evidence items have been documented at this time.'}

TRANSACTION TIMELINE
--------------------
- ${data.transactionDate}: Transaction initiated and processed for ${amount}
- ${data.transactionDate}: Authorization obtained and order confirmed
- ${data.disputeDate}: Chargeback filed by cardholder
- ${today}: Merchant response submitted

RESPONSE STRATEGY
-----------------
${data.reasonCodeData.responseStrategy}

CONCLUSION
----------
Based on the evidence provided above, the Merchant respectfully requests that this chargeback be reversed and the disputed amount of ${amount} be returned to the Merchant's account. The transaction was legitimate, properly authorized, and the ${data.reasonCodeData.category === 'Consumer' ? 'goods/services were delivered as described' : 'transaction was processed correctly and in accordance with all applicable rules'}.

The Merchant has made every reasonable effort to resolve this dispute and stands behind the legitimacy of this transaction.

Respectfully submitted,

${data.merchantName}
Response submitted via ChargebackKit
Generated: ${today}

---
This response was generated by ChargebackKit — chargebackkit.com
Professional chargeback evidence packages optimized for your reason code.`;
}
