export const SEED_DISPUTES = [
  {
    order_id: 'TGP-2847',
    merchant_name: 'TechGear Pro',
    customer_name: 'James Morrison',
    customer_email: 'j.morrison@email.com',
    transaction_date: (() => { const d = new Date(); d.setDate(d.getDate() - 20); return d.toISOString().split('T')[0]; })(),
    transaction_amount: 189.99,
    card_network: 'visa',
    reason_code: '10.4',
    reason_description: 'Other Fraud — Card Absent Environment',
    dispute_date: (() => { const d = new Date(); d.setDate(d.getDate() - 10); return d.toISOString().split('T')[0]; })(),
    response_deadline: (() => { const d = new Date(); d.setDate(d.getDate() + 5); return d.toISOString().split('T')[0]; })(),
    status: 'evidence_submitted',
    evidence_score: 82,
  },
  {
    order_id: 'TGP-3192',
    merchant_name: 'TechGear Pro',
    customer_name: 'Sarah Chen',
    customer_email: 's.chen@email.com',
    transaction_date: (() => { const d = new Date(); d.setDate(d.getDate() - 15); return d.toISOString().split('T')[0]; })(),
    transaction_amount: 449.00,
    card_network: 'mastercard',
    reason_code: '4837',
    reason_description: 'No Cardholder Authorization',
    dispute_date: (() => { const d = new Date(); d.setDate(d.getDate() - 5); return d.toISOString().split('T')[0]; })(),
    response_deadline: (() => { const d = new Date(); d.setDate(d.getDate() + 12); return d.toISOString().split('T')[0]; })(),
    status: 'open',
    evidence_score: 45,
  },
  {
    order_id: 'TGP-1538',
    merchant_name: 'TechGear Pro',
    customer_name: 'Robert Kim',
    customer_email: 'r.kim@email.com',
    transaction_date: (() => { const d = new Date(); d.setDate(d.getDate() - 60); return d.toISOString().split('T')[0]; })(),
    transaction_amount: 79.99,
    card_network: 'visa',
    reason_code: '13.1',
    reason_description: 'Merchandise/Services Not Received',
    dispute_date: (() => { const d = new Date(); d.setDate(d.getDate() - 45); return d.toISOString().split('T')[0]; })(),
    response_deadline: (() => { const d = new Date(); d.setDate(d.getDate() - 15); return d.toISOString().split('T')[0]; })(),
    status: 'won',
    evidence_score: 91,
  },
  {
    order_id: 'TGP-2103',
    merchant_name: 'TechGear Pro',
    customer_name: 'Maria Garcia',
    customer_email: 'm.garcia@email.com',
    transaction_date: (() => { const d = new Date(); d.setDate(d.getDate() - 50); return d.toISOString().split('T')[0]; })(),
    transaction_amount: 299.50,
    card_network: 'visa',
    reason_code: '13.3',
    reason_description: 'Not as Described',
    dispute_date: (() => { const d = new Date(); d.setDate(d.getDate() - 38); return d.toISOString().split('T')[0]; })(),
    response_deadline: (() => { const d = new Date(); d.setDate(d.getDate() - 8); return d.toISOString().split('T')[0]; })(),
    status: 'lost',
    evidence_score: 38,
  },
  {
    order_id: 'TGP-3847',
    merchant_name: 'TechGear Pro',
    customer_name: 'David Thompson',
    customer_email: 'd.thompson@email.com',
    transaction_date: (() => { const d = new Date(); d.setDate(d.getDate() - 45); return d.toISOString().split('T')[0]; })(),
    transaction_amount: 159.00,
    card_network: 'visa',
    reason_code: '13.2',
    reason_description: 'Cancelled Recurring Transaction',
    dispute_date: (() => { const d = new Date(); d.setDate(d.getDate() - 32); return d.toISOString().split('T')[0]; })(),
    response_deadline: (() => { const d = new Date(); d.setDate(d.getDate() - 2); return d.toISOString().split('T')[0]; })(),
    status: 'won',
    evidence_score: 78,
  },
  {
    order_id: 'TGP-4201',
    merchant_name: 'TechGear Pro',
    customer_name: 'Jennifer Wilson',
    customer_email: 'j.wilson@email.com',
    transaction_date: (() => { const d = new Date(); d.setDate(d.getDate() - 10); return d.toISOString().split('T')[0]; })(),
    transaction_amount: 89.99,
    card_network: 'mastercard',
    reason_code: '4853',
    reason_description: 'Cardholder Dispute',
    dispute_date: (() => { const d = new Date(); d.setDate(d.getDate() - 3); return d.toISOString().split('T')[0]; })(),
    response_deadline: (() => { const d = new Date(); d.setDate(d.getDate() + 18); return d.toISOString().split('T')[0]; })(),
    status: 'open',
    evidence_score: 0,
  },
  {
    order_id: 'TGP-2956',
    merchant_name: 'TechGear Pro',
    customer_name: 'Michael Brown',
    customer_email: 'm.brown@email.com',
    transaction_date: (() => { const d = new Date(); d.setDate(d.getDate() - 25); return d.toISOString().split('T')[0]; })(),
    transaction_amount: 549.99,
    card_network: 'visa',
    reason_code: '10.4',
    reason_description: 'Other Fraud — Card Absent Environment',
    dispute_date: (() => { const d = new Date(); d.setDate(d.getDate() - 12); return d.toISOString().split('T')[0]; })(),
    response_deadline: (() => { const d = new Date(); d.setDate(d.getDate() + 3); return d.toISOString().split('T')[0]; })(),
    status: 'evidence_submitted',
    evidence_score: 73,
  },
  {
    order_id: 'TGP-1784',
    merchant_name: 'TechGear Pro',
    customer_name: 'Lisa Anderson',
    customer_email: 'l.anderson@email.com',
    transaction_date: (() => { const d = new Date(); d.setDate(d.getDate() - 70); return d.toISOString().split('T')[0]; })(),
    transaction_amount: 34.99,
    card_network: 'visa',
    reason_code: '12.6',
    reason_description: 'Duplicate Processing',
    dispute_date: (() => { const d = new Date(); d.setDate(d.getDate() - 55); return d.toISOString().split('T')[0]; })(),
    response_deadline: (() => { const d = new Date(); d.setDate(d.getDate() - 25); return d.toISOString().split('T')[0]; })(),
    status: 'won',
    evidence_score: 95,
  },
];
