'use client'

import { useEffect, useState, useCallback } from 'react'
import Link from 'next/link'
import { useParams } from 'next/navigation'
import { getReasonCode } from '@/lib/reason-codes'
import { generateResponseLetter } from '@/lib/letter-generator'

interface EvidenceItem {
  id: string
  evidence_type: string
  description: string
  is_provided: boolean
}

interface Dispute {
  id: string
  order_id: string
  merchant_name: string
  customer_name: string
  customer_email: string
  transaction_date: string
  transaction_amount: number
  card_network: string
  reason_code: string
  reason_description: string
  dispute_date: string
  response_deadline: string
  status: string
  evidence_score: number
  evidence_items: EvidenceItem[]
}

const EVIDENCE_LABELS: Record<string, string> = {
  transaction_receipt: 'Transaction Receipt',
  delivery_proof: 'Delivery Proof',
  customer_communication: 'Customer Communication',
  refund_policy: 'Refund Policy',
  usage_logs: 'Usage Logs',
  avs_cvv_match: 'AVS/CVV Match Data',
  prior_transactions: 'Prior Transactions',
  billing_descriptor: 'Billing Descriptor',
  signed_contract: 'Signed Contract/Agreement',
  other: 'Other Evidence',
}

export default function EvidencePackagePage() {
  const params = useParams()
  const [dispute, setDispute] = useState<Dispute | null>(null)
  const [loading, setLoading] = useState(true)

  const loadDispute = useCallback(async () => {
    const res = await fetch(`/api/disputes/${params.id}`)
    if (res.ok) {
      const data = await res.json()
      setDispute(data)
    }
    setLoading(false)
  }, [params.id])

  useEffect(() => {
    loadDispute()
  }, [loadDispute])

  if (loading) return <div className="p-8 text-slate-400">Loading evidence package...</div>
  if (!dispute) return <div className="p-8 text-slate-400">Dispute not found.</div>

  const rc = getReasonCode(dispute.reason_code)
  const letter = rc ? generateResponseLetter({
    merchantName: dispute.merchant_name,
    orderId: dispute.order_id,
    customerName: dispute.customer_name,
    transactionDate: dispute.transaction_date,
    transactionAmount: Number(dispute.transaction_amount),
    cardNetwork: dispute.card_network,
    reasonCode: dispute.reason_code,
    reasonCodeData: rc,
    disputeDate: dispute.dispute_date,
    responseDeadline: dispute.response_deadline,
    evidenceItems: (dispute.evidence_items || []).map(e => ({
      type: e.evidence_type,
      description: e.description,
      isProvided: e.is_provided,
    })),
  }) : ''

  const providedEvidence = (dispute.evidence_items || []).filter(e => e.is_provided)

  return (
    <div className="min-h-screen bg-slate-950">
      {/* Print Controls (hidden on print) */}
      <div className="no-print sticky top-0 z-50 bg-slate-900 border-b border-slate-800 px-8 py-4">
        <div className="flex items-center justify-between max-w-4xl mx-auto">
          <div className="flex items-center gap-4">
            <Link href={`/dashboard/disputes/${dispute.id}`} className="text-slate-400 hover:text-white text-sm">
              ← Back to Dispute
            </Link>
            <span className="text-slate-600">|</span>
            <h1 className="text-white font-semibold">Evidence Package — {dispute.order_id}</h1>
          </div>
          <button
            onClick={() => window.print()}
            className="bg-amber-500 hover:bg-amber-400 text-slate-950 font-bold px-4 py-2 rounded-lg text-sm transition-colors"
          >
            Print / Save PDF
          </button>
        </div>
      </div>

      {/* Print Content */}
      <div className="print-document max-w-4xl mx-auto p-8">
        {/* Header */}
        <div className="text-center mb-8 pb-6 border-b border-slate-700 no-print">
          <h2 className="text-2xl font-bold text-white">Chargeback Evidence Package</h2>
          <p className="text-slate-400 mt-1">Generated by ChargebackKit</p>
        </div>

        {/* Evidence Score Banner */}
        <div className={`no-print mb-6 rounded-xl p-4 border ${dispute.evidence_score >= 85 ? 'bg-emerald-500/10 border-emerald-500/30' : dispute.evidence_score >= 70 ? 'bg-green-500/10 border-green-500/30' : dispute.evidence_score >= 50 ? 'bg-amber-500/10 border-amber-500/30' : 'bg-red-500/10 border-red-500/30'}`}>
          <div className="flex items-center justify-between">
            <span className="text-white font-medium">Evidence Strength Score</span>
            <span className="text-3xl font-bold text-white">{dispute.evidence_score}<span className="text-slate-400 text-sm font-normal">/100</span></span>
          </div>
          <div className="h-2 bg-slate-700 rounded-full mt-2 overflow-hidden">
            <div className={`h-2 rounded-full ${dispute.evidence_score < 50 ? 'bg-red-500' : dispute.evidence_score < 70 ? 'bg-amber-500' : dispute.evidence_score < 85 ? 'bg-green-500' : 'bg-emerald-500'}`} style={{ width: `${dispute.evidence_score}%` }} />
          </div>
        </div>

        {/* Evidence Checklist */}
        <div className="mb-8">
          <h3 className="text-lg font-bold text-white mb-4 no-print">Evidence Provided ({providedEvidence.length} items)</h3>
          <div className="space-y-2">
            {providedEvidence.map((item, idx) => (
              <div key={item.id} className="flex items-start gap-3 bg-slate-900 border border-slate-700 rounded-lg p-3 no-print">
                <span className="text-emerald-400 font-bold">{idx + 1}.</span>
                <div>
                  <p className="text-white font-medium text-sm">{EVIDENCE_LABELS[item.evidence_type] || item.evidence_type}</p>
                  {item.description && <p className="text-slate-400 text-xs mt-0.5">{item.description}</p>}
                </div>
              </div>
            ))}
            {providedEvidence.length === 0 && (
              <p className="text-slate-500 text-sm no-print">No evidence items marked as provided.</p>
            )}
          </div>
        </div>

        {/* Response Letter */}
        <div>
          <h3 className="text-lg font-bold text-white mb-4 no-print">Response Letter</h3>
          <div className="bg-slate-900 border border-slate-700 rounded-xl p-6 font-mono text-sm text-slate-200 whitespace-pre-wrap leading-relaxed no-print">
            {letter}
          </div>
        </div>

        {/* Print-only version */}
        <div className="print-only">
          <h1 style={{ fontSize: '24px', fontWeight: 'bold', marginBottom: '8px' }}>Chargeback Evidence Package</h1>
          <p style={{ marginBottom: '4px' }}>Order: {dispute.order_id} | Amount: ${Number(dispute.transaction_amount).toFixed(2)}</p>
          <p style={{ marginBottom: '16px' }}>Reason Code: {dispute.card_network?.toUpperCase()} {dispute.reason_code} | Evidence Score: {dispute.evidence_score}/100</p>
          <hr style={{ marginBottom: '16px' }} />
          <pre style={{ whiteSpace: 'pre-wrap', fontFamily: 'monospace', fontSize: '12px', lineHeight: '1.6' }}>{letter}</pre>
        </div>
      </div>
    </div>
  )
}
